---
sensor:
  # Battery %
  - platform: adc
    pin: 33
    name: '${devicename} Battery'
    id: '${devicename}_percent'
    attenuation: 11db
    accuracy_decimals: 2
    unit_of_measurement: '%'
    filters:
      - multiply: 2
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 3.18 -> 0.0
          - 4.20 -> 100.0
    update_interval: ${update_interval}
