---
name: Build

on: [push, pull_request]

jobs:
  build:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        file:
          - LILYGO-T-Higrow-ESP32.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.5.2
        with:
          yaml_file: ${{ matrix.file }}
  publish:
    if: ${{ github.ref == 'main' }}
    needs: build
    name: Publish firmware
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: LILYGO-T-Higrow-ESP32.yaml
      name: ESPHome Plant monitor
      manifest_filename: lilygo-t-higrow-manifest.json
      clean: false
