---
name: Test PR

on: [pull_request]

jobs:
  build:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - LILYGO-T-Higrow-ESP32.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v1.5.2
        with:
          yaml_file: ${{ matrix.file }}
